# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Use DotNet Core 3.1'
  inputs:
    version: 3.x
    includePreviewVersions: false

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'NHSAPP-BuyingCatalogue'
    azureContainerRegistry: '{"loginServer":"buyingcat01.azurecr.io", "id" : "/subscriptions/7b12a8a2-f06f-456f-b6f9-aa2d92e0b2ec/resourceGroups/BCadminrepo/providers/Microsoft.ContainerRegistry/registries/buyingcat01"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up --scale chrome=4 -d'
    arguments: ''

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: '
    export BROWSER=chrome &&
    export SERVERURL=$SERVERURL &&
    export DATABASENAME=$DATABASENAME &&
    export DBUSER=$DBUSER &&
    export DBPASSWORD=$DBPASSWORD &&
    export HUBURL=$HUBURL &&
    export MPURL=$MPURL &&
    dotnet test src/ -v n'